### PR TITLE
Prettier, ESLint and TypeScript Migration

### PR DESCRIPTION
**Pull request by SkyIsTheLimit**

### CODE REVIEW

**Comment by steveand117** [comment]
What exactly does this do?

**Comment by codelastnight** [comment]
✅ runs on my pc. 
had an issue where `client` was spitting out a compilation error `Plugin “react” was conflicted between “.eslintrc.js» eslint-config-react-app` , but it was fixed after i hit ctrl+s on the package.json.

**Comment by codelastnight** [comment]
having some issues running the PR locally
- authentication fail error on mongodb, both server and fetch dev:run fails( however i can connect on staging branch, same mongo server)
- in `server`, `dist` folder wasn't added to `.git-ignore`
- stmux package missing from top level package.json (but exists in `server` and `fetch` package.json) 
  - also on windows, stmux requires windows-build-tools to be installed, but if u use nvm-windows or nvs, it is not installed by default (there is a simple workaround, but might be worth mentioning idk)

**Comment by steveand117** [comment]
Running into similar issues with mongo authentication as simon ^^ perhaps this is related? Or not, I'm using the old run dev here.
image

All the other comments I agree with as well.

**Comment by steveand117** [comment]
There's also an issue where the posts are not pulled immediately (seems you can get them to pull by clearing all filters)

**Pull request merged**
